---
- name: windows test playbook
  hosts: windows
  gather_facts: false
  tasks:
    - local_action:
        module: shell
        _raw_params: 'ls -al'

    - local_action:
        module: shell
        _raw_params: 'kinit pavery@LAB.INT -k -t username.keytab'

    - name: ping windows box
      win_ping:
